version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  rabbit:
    container_name: rabbit
    image: rabbitmq
    ports:
      - 15672:15672
      - 15671:15671
      - 5672:5672
    volumes:
      - ./rabbitmq/lib:/var/lib/rabbitmq

  auth:
    container_name: auth-service
    restart: always
    build: ./micro-services/authentication-service
    depends_on:
      - rabbit
    ports:
      - "3000:3000"
    links:
      - mongo
      - rabbit
  post:
    container_name: post-service
    restart: always
    build: ./micro-services/posts-service
    depends_on:
      - rabbit
    ports:
      - "8000:8000"
    links:
      - mongo
      - rabbit

  user:
    container_name: user-service
    restart: always
    build: ./micro-services/users-service
    # command: ["./wait_for.sh"]
    depends_on:
      - rabbit
    ports:
      - "4000:4000"
    links:
      - mongo
      - rabbit
